# https://github.com/KnpLabs/geekweek12/wiki/Routing

App:Admin:index: /admin

App:Page: 
    prefix: /admin/page
    resources: [edit, update, delete]

# homepage:
#     pattern: /
#     defaults: { _controller: FrameworkBundle:Template:template, template: 'App::homepage.html.twig' }
frontend:
    pattern: "/{page}"
    defaults:
        _controller: App:Page:home
    requirements:
        page: (.*)