# https://github.com/KnpLabs/geekweek12/wiki/Routing

App:Admin:index: /admin

App:Page: 
    prefix: /admin/page
    resources: [edit, update, delete]

App:News:
    prefix: /admin/news
    resources: [edit, update, delete]

app_news_show:
    pattern: "/actualites/{uri}"
    defaults:
        _controller: App:News:show
    requirements:
        uri: (.*)

App:Admin:browseImage: /browse-ckeditor-image

app_upload_ckeditor_image:
    pattern: '/upload_ckeditor_image'
    defaults:
        _controller: App:Admin:uploadImage
    methods: POST

# homepage:
#     pattern: /
#     defaults: { _controller: FrameworkBundle:Template:template, template: 'App::homepage.html.twig' }
frontend:
    pattern: "/{uri}"
    defaults:
        _controller: App:Page:home
    requirements:
        uri: (.*)