# http://symfony.com/doc/current/components/dependency_injection/index.html
parameters:
    app.widget_manager.class: "App\Manager\WidgetManager"

services:
    app.widget_manager:
        class: %app.widget_manager.class%