# http://symfony.com/doc/current/components/dependency_injection/index.html
parameters:
    app.widget_container.class: "App\Manager\WidgetContainer"
    app.form_type.page.class: "App\\Form\\PageType"
    app.form_type.news.class: "App\\Form\\NewsType"
    app.form_type.widget.class: "App\\Form\\WidgetType"
    app.twig.bootstrap_helper_extension.class: "App\\Twig\\BootstrapHelperExtension"
    app.twig.slider_extension.class: "App\\Twig\\SliderExtension"
    app.twig.widget_extension.class: "App\\Twig\\WidgetExtension"
    app.sidebar_container.class: "App\\Manager\\SidebarContainer"
    app.form_type.sidebar.class: "App\\Form\\SidebarType"
    app.form_type.media_category.class: "App\\Form\\MediaCategoryType"
    app.form_type.image_preview.class: "App\\Form\\ImagePreviewType"
    app.image_resize_listener.class: "App\\EventListener\\ImageResizeListener"

services:
    app.widget_container:
        class: %app.widget_container.class%
        arguments: [@service_container]
    app.sidebar_container:
        class: %app.sidebar_container.class%
        arguments: [@service_container]
    app.form.page_type:
        class: %app.form_type.page.class%
        calls:
            - ['setContainer', [ @service_container ]]
        tags:
            - {name: form.type, alias: page}
    app.form.news_type:
        class: %app.form_type.news.class%
        calls:
            - ['setContainer', [@service_container]]
        tags:
            - {name: form.type, alias: news}
    app.form.widget_type:
        class: %app.form_type.widget.class%
        calls:
            - [ 'setContainer', [@service_container]]
        tags:
            - {name: form.type, alias: 'widget'}
    app.form.sidebar_type:
        class: %app.form_type.sidebar.class%
        calls:
            - ['setContainer', [@service_container]]
        tags:
            - {name: form.type, alias: 'sidebar'}
    app.form.image_preview_type:
        class: %app.form_type.image_preview.class%
        tags:
            - {name: form.type, alias: 'image_preview'}
    app.twig.bootstrap_helper_extension:
        class: %app.twig.bootstrap_helper_extension.class%
        calls:
            - [ 'setContainer', [@service_container] ]
        tags:
            - {name: twig.extension}
    app.twig.slider_extension:
        class: %app.twig.slider_extension.class%
        calls:
            - ['setContainer', [@service_container]]
        tags:
            - {name: twig.extension}
    app.twig.widget_extension:
        class: %app.twig.widget_extension.class%
        calls:
            - ['setContainer', [@service_container]]
        tags:
            - {name: twig.extension}
    app.form.media_category_type:
        class: %app.form_type.media_category.class%
        arguments:
            - @service_container
        tags:
            - {name: form.type, alias: media_category}
    app.image_resize_listener:
        class: %app.image_resize_listener.class%
        arguments:
            - @service_container
        tags:
            - {name: doctrine.event_subscriber, connection: default}